name: Haskell CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "master"

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["9.8.2", "9.10.1", "9.12.1"]

    steps:
    - uses: actions/checkout@v4
    
    - uses: haskell-actions/setup@v2
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v4
      name: Cache ~/.cabal/packages
      with:
        path: ~/.cabal/packages
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages
    - uses: actions/cache@v4
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store

    - name: Install dependencies
      run: |
        cabal update
        cabal configure --project-file=cabal.project.ci --enable-benchmarks --enable-tests --write-ghc-environment-files=always -j2
        cabal build     --project-file=cabal.project.ci --only-dependencies all

    - name: Build & test
      run: |
        cabal build   --project-file=cabal.project.ci
        cabal haddock --project-file=cabal.project.ci
        cabal sdist   --project-file=cabal.project.ci
        cabal check
